// <auto-generated />
using Akij_Food_Crud_Operation_Api.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Akij_Food_Crud_Operation_Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Akij_Food_Crud_Operation_Api.data.ColdDrink", b =>
                {
                    b.Property<int>("ColdDrinksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ColdDrinksName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ColdDrinksId");

                    b.ToTable("ColdDrinks");

                    b.HasData(
                        new
                        {
                            ColdDrinksId = 1,
                            ColdDrinksName = "Clemon",
                            Quantity = 450m,
                            UnitPrice = 20m
                        },
                        new
                        {
                            ColdDrinksId = 2,
                            ColdDrinksName = "Frutika",
                            Quantity = 500m,
                            UnitPrice = 25m
                        },
                        new
                        {
                            ColdDrinksId = 3,
                            ColdDrinksName = "Speed",
                            Quantity = 600m,
                            UnitPrice = 30m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
